require("prototypes.signal")
require("prototypes.entity")
require("prototypes.item")
require("prototypes.recipe")

data:extend({
	signal_subgroup,
	group_signal,
	priority_signal,
	item_threshold_signal,
	fluid_threshold_signal,
	item_slots_signal,
	fluid_capacity_signal,
	combinator_entity,
	combinator_settings_entity,
	combinator_item,
	combinator_settings_item,
	combinator_recipe,
})
